# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('youtube_link', models.URLField()),
                ('youtube_embed_link', models.URLField(blank=True, max_length=100)),
                ('description', models.TextField(null=True)),
                ('related_foodentry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.FoodEntry')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
