# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 01:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import travel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=travel.models.get_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=None, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('publish_date', models.DateField(null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=travel.models.get_upload_path)),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=100, null=True)),
                ('youtube_embed_link', models.URLField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='travelpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.TravelPost'),
        ),
    ]
