# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 02:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('foodprep', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('breakfast', models.BooleanField(default=False)),
                ('entree', models.BooleanField(default=False)),
                ('snack', models.BooleanField(default=False)),
                ('desert', models.BooleanField(default=False)),
                ('savory', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('healthy', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=food.models.get_upload_path)),
                ('cover_photo', models.BooleanField(default=False)),
                ('foodentry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.FoodEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('servings', models.CharField(max_length=5)),
                ('time_unit', models.CharField(choices=[(b'minutes', b'minutes'), (b'hours', b'hours')], default=b'minutes', max_length=10)),
                ('prep_time', models.CharField(max_length=3)),
                ('cook_time', models.CharField(max_length=3)),
                ('total_time', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='foodentry',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Recipe'),
        ),
    ]
