# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='foodentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.FoodEntry'),
        ),
    ]
