# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180302_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='foodentry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.FoodEntry'),
        ),
    ]
