# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20180302_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cover_photo',
        ),
    ]
