# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20180302_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='food.Ingredient'),
        ),
    ]
