# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20180302_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[(b'lbs', b'lbs'), (b'cups', b'cups'), (b'tsp', b'tsp'), (b'blank', b'')], max_length=10),
        ),
    ]
