# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=food.models.get_image_upload_path),
        ),
    ]
