# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20180303_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='title',
        ),
        migrations.AddField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
