# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_delete_fullingredientlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time_unit',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.CharField(max_length=20),
        ),
    ]
