# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_auto_20180303_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodentry',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
