# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_auto_20180304_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='foodentry',
            new_name='foodpost',
        ),
    ]
