# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_auto_20180304_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
