# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_remove_foodpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='foodpost',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
