# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0030_auto_20180304_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=food.models.get_image_upload_path),
        ),
    ]
