# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0031_auto_20180304_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to=food.models.get_upload_path),
        ),
    ]
