# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0035_auto_20180305_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
