# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0037_auto_20180305_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='foodprep',
        ),
    ]
