# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0038_auto_20180305_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='entree',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='healthy',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='savory',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='snack',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='vegetarian',
        ),
        migrations.AddField(
            model_name='recipe',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dessert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='entree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='healthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='savory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='snack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
