# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0040_recipe_food_prep'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='youtube_embed_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodpost',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
