# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0041_auto_20180308_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='post_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
