# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beauty',
            new_name='BeautyPost',
        ),
    ]
